chore: set custom user agent and namespace
ExpediaGroup/lodging-connectivity-java-sdk pull request #78
Opened 2024-10-27 13:07 UTC by OmarAlJarrah

# Situation
* User agents are automatically set by the Google API client. The default value generated by the client does not follow our format for the user agent header, which is used in our metrics collection.

# Task
Update the user agent format to follow our custom SDK format.

# Action
Updated the user agent header value.

# Testing
**TBA**

# Results
User agent now follows our conventions.

# Notes
## Why set the user agent value in a subclass of the `CommonGoogleClientRequestInitializer` and not the usual `HttpRequestInitializer`?
The user agent value was done in the `ApiClientRequestInitializer` class, which is a subclass of `CommonGoogleClientRequestInitializer`. The `CommonGoogleClientRequestInitializer` is a higher layer compared to the `HttpRequestInitializer`. 

The `CommonGoogleClientRequestInitializer.initialize()` super method handles some internal request configurations, including automatically adding some headers for us (e.g. `user-agent`). Also, the initializer handles executing the initialize method in sub `HttpRequestInitializer` instances.

## Why rename `namespace` value in all clients?
We want to insure a consistent namespace for each client. The namespace is an SDK value, in other words, a client agnostic value that should not be coupled with each client.

2024-10-28 19:14 UTC, Mohammad-Dwairi commented on code/src/main/kotlin/com/expediagroup/sdk/v2/core/configuration/SdkMetadata.kt
> +                FileInputStream("gradle.properties").use {
did you verify if this file is available in the final Jar file? did it work fine at runtime?

2024-10-28 19:45 UTC, Mohammad-Dwairi commented
Can we consider reading the properties needed to build the user agent from a custom resources file instead of the build tool properties? This will make the solution applicable to any setup regardless of the used build tool.

2024-10-29 15:00 UTC, mohnoor94 requested changes

2024-10-29 15:25 UTC, Mohammad-Dwairi approved these changes

2024-10-30 13:05 UTC, mohnoor94 approved these changes
LGTM.

2024-10-30 15:21 UTC, merged